### ISSUE TITLE
שיפור רישום עצמי לארועים

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/food-basket-delivery#727]
# todo
- [ ] אפשרות לקבוע לינק לארוע בודד 
- [ ] לינק לאירועים לכולם ולינק לארועים לארגון ספציפי
- [ ] כאשר מתנדב מבטל רישום - שירשם שהוא ביטל (לא למחוק)
- [ ] make sure that on mobile the card will be full width
- [ ] maybe group events by date
- [ ] not validate phone and name if context is authorized
- [ ] notification of volunteer changes
- [ ] make sure the small image is correct
- [ ] fix register donor - so there will not be invalid address error on submit
- [ ] add create new event button
- [ ] can't create new event - get error can't read address helper of null
- [ ] סינון לפי ימים
- [ ] סינון לפי עיר
- [ ] הצגת תארים כיום ביחס לעכשיו וכו....
- [ ] להוסיף סוג התנדבות - גם כסינון
- [ ] לאפשר לארגון להגדיר שהוא לא משתתף בחגיגה
- [ ] להוריד
# to test
- [ ] אפשרות לראות את האירועים של ארגון לפני שנרשמים בכתובת: /men/register
 - [ ] אפשרות להרשם לפני LOGIN לארועים של ארגון
- [ ] אפשרות לראות ארועים של כל הארגונים במרוכז /guest/register
